### ISSUE TITLE
Python 3.6 os.path.commonprefix expects List

### ISSUE THREAD

**Issue by rakhimov** [rakhimov/cppdep#42]
```
  File "/.../cppdep/cppdep.py", line 92, in path_common
    path = os.path.commonprefix(paths)
  File "/home/olzhas/temp/pyenv/lib/python3.6/genericpath.py", line 76, in commonprefix
    if not isinstance(m[0], (list, tuple)):
TypeError: 'set' object does not support indexing
```

**Comment by BartVandewoestyne** [comment]
Same problem here with Python 3.8.1:
```
D:\SVN\some\project>py -V
Python 3.8.1

D:\SVN\some\project>py -m cppdep -c .cppdep.yml
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python38-32\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files (x86)\Python38-32\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\cppdep\__main__.py", line 83, in <module>
    main()
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\cppdep\__main__.py", line 57, in main
    analysis = cppdep.DependencyAnalysis(args.config)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\cppdep\cppdep.py", line 613, in __init__
    self.__parse_config(config_file)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\cppdep\cppdep.py", line 636, in __parse_config
    DependencyAnalysis.__add_package_group(pkg_group_config,
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\cppdep\cppdep.py", line 661, in __add_package_group
    Package(pkg_config['name'],
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\cppdep\cppdep.py", line 378, in __init__
    self.root = path_common(self.src_paths)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\cppdep\cppdep.py", line 92, in path_common
    path = os.path.commonprefix(paths)
  File "C:\Program Files (x86)\Python38-32\lib\genericpath.py", line 76, in commonprefix
    if not isinstance(m[0], (list, tuple)):
TypeError: 'set' object is not subscriptable
```
